### ISSUE TITLE
Won't zoom out

### ISSUE THREAD

**Issue by kristianmarkuy** [chiragmakwana000/nodemedia-client-with-zoom#1]

**Comment by chiragmakwana000** [comment]
@kristianmarkuy 

Please add code snippet ?

**Comment by DhavalGosai** [comment]
Hi @kristianmarkuy, the zoom-out functionality has already been implemented. Could you please share the exact issue you're encountering or provide relevant code snippets? This will help me identify and resolve the problem more effectively. Thank you!
