### ISSUE TITLE
pod is not installing in react native ios

### ISSUE THREAD

**Issue by Neelshah768** [chiragmakwana000/nodemedia-client-with-zoom#2]
[!] Error installing NodeMediaClient
[!] /opt/homebrew/bin/git clone https://github.com/NodeMedia/NodeMediaClient-iOS.git /var/folders/tr/mhp0shbd4l741xk5kykx6rzh0000gn/T/d20240519-8922-1n1grve --template= --single-branch --depth 1 --branch 2.8.2

Cloning into '/var/folders/tr/mhp0shbd4l741xk5kykx6rzh0000gn/T/d20240519-8922-1n1grve'...
warning: Could not find remote branch 2.8.2 to clone.
fatal: Remote branch 2.8.2 not found in upstream origin

I got this error everytime when try to install pods into my react native project.

**Comment by DhavalGosai** [comment]
- Updated package dependencies to address the pod installation issue.
- Reinstalled pods to ensure correct configuration and setup.
